import Link from 'next/link';
import { origin, companyId, compliance } from '@/lib/compliance';
import { centerPath, complianceLocales, getCenterCopy, type ComplianceLocale } from '@/lib/complianceLocale';
import { SUPPORTED_LANGUAGES } from '@/lib/i18n';
import { batteryModels } from './BatteryDocumentation';
import CenterSearch from './CenterSearch';
import InquiryForm from './InquiryForm';
export default async function CenterPage({locale='en'}:{locale?:ComplianceLocale}) {
 const c=await getCenterCopy(locale); const url=origin+centerPath(locale);
 const schema={'@context':'https://schema.org','@graph':[{'@type':'CollectionPage','@id':url+'#webpage',url,name:c.title,description:c.description,inLanguage:locale,dateModified:'2026-09-06',isPartOf:{'@id':origin+'/#website'},publisher:{'@id':companyId}},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:c.home,item:origin},{'@type':'ListItem',position:2,name:c.title,item:url}]}]};
 return <article className="evidence-page" lang={locale} dir={['ar','he'].includes(locale)?'rtl':'ltr'}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/><nav className="evidence-breadcrumb" aria-label={c.home}><Link href="/">{c.home}</Link> / {c.title}</nav><header className="evidence-intro"><span className="evidence-eyebrow">VSZAPOWER</span><h1>{c.title}</h1><p>{c.lead}</p><a className="btn-primary" href="#document-request">{c.requestModel}</a></header><nav className="evidence-languages" aria-label={c.languages}>{complianceLocales.map(l=><Link key={l} href={centerPath(l)} hrefLang={l} lang={l} aria-current={l===locale?'page':undefined}>{SUPPORTED_LANGUAGES.find(x=>x.code===l)?.nativeName}</Link>)}</nav><section className="evidence-section"><h2>{c.designs}</h2><CenterSearch copy={c}/></section><section className="evidence-section" id="battery-documentation"><h2>{c.batteries}</h2><p>{c.batteryText}</p><div className="battery-documentation-grid">{batteryModels.map(model=><article key={model} className="evidence-card"><h3 dir="ltr">{model}</h3><a href="#document-request">{c.requestModel} · <bdi>{model}</bdi></a></article>)}</div><p>{c.batterySafety}</p></section><aside className="evidence-note"><h2>{c.scopeTitle}</h2><p>{c.scope}</p></aside><section className="evidence-section"><h2>{c.faq}</h2>{c.questions.map((q,i)=><details className="evidence-faq" key={q}><summary>{q}</summary><p>{c.answers[i]}</p></details>)}</section><InquiryForm copy={c}/><nav className="evidence-related"><Link href="/about-vszapower" hrefLang="en">{c.about}</Link><Link href="/coin-cell-charger-manufacturer" hrefLang="en">{c.manufacturer}</Link><Link href="/academy">{c.academy}</Link></nav><p className="evidence-small">{c.reviewed}: <time dateTime={compliance.contentReviewedAt}>{compliance.contentReviewedAt}</time></p></article>;
}
