import Link from 'next/link';
import copy from '@/content/compliance/copy.json';
import { products, compliance } from '@/lib/compliance';
import { PageIntro, PageSchema, RelatedLinks, ProductCard, ScopeNote } from './Shared';
import ModelSearch from './ModelSearch';
import InquiryForm from './InquiryForm';
import BatteryDocumentation from './BatteryDocumentation';
export default function EditorialPage({kind}:{kind:keyof typeof copy}){
 const c=copy[kind]; const path={center:'/compliance',about:'/about-vszapower',manufacturer:'/coin-cell-charger-manufacturer'}[kind];
 return <article className="evidence-page" lang="en"><PageSchema title={c.H1} path={path} type={kind==='about'?'AboutPage':kind==='center'?'CollectionPage':'WebPage'}/><nav aria-label="Breadcrumb" className="evidence-breadcrumb"><Link href="/">Home</Link> / {c.H1}</nav><PageIntro title={c.H1} lead={c.Lead}><div className="evidence-actions"><a className="btn-primary" href="#document-request">{kind==='manufacturer'?'Request a wholesale quote':'Request documents'}</a><Link href={kind==='center'?'/about-vszapower':'/compliance'}>{kind==='center'?'About VSZAPOWER':'View test documentation'} →</Link></div></PageIntro>{c.sections.map(s=><section className="evidence-section" key={s.title}><h2>{s.title}</h2>{s.paragraphs.map(p=><p key={p}>{p}</p>)}{s.title==='Find documentation for your product'&&<ModelSearch/>}{s.title==='Compare charger designs'&&<div className="evidence-grid">{products.map(p=><ProductCard product={p} key={p.id}/>)}</div>}{(s.title==='Battery documentation requests'||s.title==='Battery sourcing and product versions')&&<BatteryDocumentation/>}{s.title==='Company and product focus'&&<dl className="evidence-facts">{Object.entries({Brand:'VSZAPOWER',Company:'Shenzhen Weizan Technology Co., Ltd.',Location:'Shenzhen, Guangdong, China','Product focus':'Rechargeable coin-cell chargers and batteries','Commercial enquiries':'Wholesale, branding and packaging projects'}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>}{s.title==='Charger manufacturing documentation'&&<div className="evidence-grid">{products.map(p=><ProductCard product={p} key={p.id}/>)}</div>}{s.title==='How an OEM enquiry works'&&<ol><li>Specify the rechargeable cell and application.</li><li>Select a charger design and describe the expected quantity and packaging.</li><li>Confirm specifications, samples and the documentation needed for the target market.</li></ol>}{s.faqs.map(f=><details className="evidence-faq" key={f.q}><summary>{f.q}</summary><p>{f.a}</p></details>)}</section>)}<ScopeNote/><InquiryForm quote={kind==='manufacturer'}/><RelatedLinks/><p className="evidence-small">Content reviewed: <time dateTime={compliance.contentReviewedAt}>{compliance.contentReviewedAt}</time></p></article>;
}
