 'use client';
import { useRef, useState } from 'react';
import en from '@/content/compliance/locales/en.json';
import type { CenterCopy } from '@/lib/complianceLocale';
export default function InquiryForm({product='Model-specific documentation',quote=false,copy:c=en}: {product?:string;quote?:boolean;copy?:CenterCopy}) {
 const [status,setStatus]=useState<'idle'|'sending'|'success'|'error'>('idle'); const busy=useRef(false);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy.current)return;busy.current=true;setStatus('sending');const f=new FormData(e.currentTarget);
 try{const response=await fetch('/api/inquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:f.get('company')||'Commercial buyer',contact:f.get('email'),company:f.get('company'),country:f.get('market'),product,message:`Specification: ${f.get('specification')}\nQuantity: ${f.get('quantity')}\n${f.get('message')}`,website:f.get('website')})});const body=await response.json();if(!response.ok||body.success!==true)throw new Error('Submission failed');setStatus('success');}catch{setStatus('error');}finally{busy.current=false;}}
 return <section id="document-request" className="evidence-section evidence-request"><div><span className="evidence-eyebrow">{c.requestModel}</span><h2>{quote?'Request a charger quotation':c.formTitle}</h2><p>{c.formIntro}</p><p className="evidence-small">{c.privacy}</p></div><form onSubmit={submit} className="evidence-form"><p><strong>{product==='Model-specific documentation'?c.formTitle:product}</strong></p><label>{c.email}<input name="email" type="email" required maxLength={254} autoComplete="email"/></label><label>{c.company}<input name="company" maxLength={200} autoComplete="organization"/></label><label>{c.specification}<input name="specification" required maxLength={500}/></label><div className="evidence-form-row"><label>{c.quantity}<input name="quantity" required={quote} maxLength={100}/></label><label>{c.market}<input name="market" required maxLength={100}/></label></div><label>{c.purpose}<textarea name="message" rows={4} maxLength={3000}/></label><div hidden><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div><button className="btn-primary" disabled={status==='sending'||status==='success'}>{status==='sending'?c.sending:status==='success'?c.received:c.send}</button><p role="status" aria-live="polite">{status==='success'?c.success:status==='error'?c.error:''}</p></form></section>;
}
