import { notFound } from 'next/navigation';
import Link from 'next/link';
import { products, pageMetadata, compliance } from '@/lib/compliance';
import { PageIntro, PageSchema, ScopeNote, EvidenceTable, RelatedLinks } from '@/components/compliance/Shared';
import InquiryForm from '@/components/compliance/InquiryForm';
export const dynamicParams=false;
export function generateStaticParams(){return products.map(p=>({slug:p.id}));}
export function generateMetadata({params}:{params:{slug:string}}){const p=products.find(p=>p.id===params.slug);if(!p)return {};return pageMetadata(`${p.model} ${p.design} Test Reports | VSZAPOWER`,`Review ${p.model} ${p.design}, report series ${p.reportSeries}: EMC and RoHS test scope, standards, dates and document requests.`,p.path);}
export default function Page({params}:{params:{slug:string}}){const p=products.find(p=>p.id===params.slug);if(!p)notFound();const [emc,voc,rohs]=p.documents;const title=`${p.model} ${p.design} Compliance Documentation`;
 return <article className="evidence-page" lang="en"><PageSchema title={title} path={p.path} product={p}/><nav className="evidence-breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link> / <Link href="/compliance">Compliance Center</Link> / {p.model} {p.design}</nav><PageIntro title={title} lead={`This summary covers the ${p.model} ${p.design.toLowerCase()} configuration associated with report series ${p.reportSeries}. Its EMC report lists ${emc.standards.join(' and ')}, with PASS results for the tests in the report summary. A separate RoHS report records a Pass result for the tested materials of the submitted sample.`}/><section className="evidence-section"><h2>Identify this charger design</h2><figure className="evidence-sample evidence-sample-detail"><img src={p.image} alt={`${p.model} ${p.design} test sample, ${p.reportSeries}`} width="800" height="600"/><figcaption>Test sample photo · {emc.number}. Photo identifies the tested configuration.</figcaption></figure><p>Match {p.model} — {p.design} with report series {p.reportSeries}. Documentation for another design or battery bundle does not transfer to this configuration.</p><dl className="evidence-facts"><div><dt>Model / design</dt><dd>{p.model} / {p.design}</dd></div><div><dt>Report series</dt><dd>{p.reportSeries}</dd></div><div><dt>Input recorded in EMC report</dt><dd>DC 5V</dd></div></dl></section><EvidenceTable product={p}/><section className="evidence-section"><h2>EMC test scope</h2><p>Report {emc.number}, issued on {emc.issueDate} by {emc.laboratory}, records the EMC tests for the submitted sample. Verification of Conformity {voc.number} refers to that report and the EMC Directive 2014/30/EU. This does not by itself establish every requirement that may apply to CE marking of the finished product.</p><p>A Verification of Conformity is not an EU Declaration of Conformity.</p></section><section className="evidence-section"><h2>RoHS test scope</h2><p>Report {rohs.number}, issued on {rohs.issueDate}, records a Pass result for the requested restricted-substance tests on the tested materials of the submitted sample, with reference to Directive 2011/65/EU and amendment (EU) 2015/863. The result is not a claim of zero restricted substances.</p><p>{rohs.scope}.</p></section><ScopeNote/><InquiryForm product={`${p.model} — ${p.design} / ${p.reportSeries}`}/><RelatedLinks/><p className="evidence-small">Content reviewed: {compliance.contentReviewedAt}</p></article>;
}
